//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SMO.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_SMO_InferenceEngine_EMI::runEMITest___VOID,
    Library_SMO_InferenceEngine_EMI::EMIDriver___BOOLEAN__SZARRAY_U4,
    NULL,
    Library_SMO_InferenceEngine_FastGRNN::runFastGRNNTest___VOID,
    Library_SMO_InferenceEngine_FastGRNN::FastGRNNDriver___BOOLEAN__SZARRAY_U4,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SMO =
{
    "SMO", 
    0x16B9893B,
    method_lookup
};

