//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SMO.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_SMO_InferenceEngine_SMO::runEMITest___VOID,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SMO =
{
    "SMO", 
    0x0C6E078B,
    method_lookup
};

