//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SMO_H_
#define _SMO_H_

#include <TinyCLR_Interop.h>
struct Library_SMO_InferenceEngine_SMO
{
    TINYCLR_NATIVE_DECLARE(runEMITest___VOID);
    TINYCLR_NATIVE_DECLARE(EMIDriver___VOID__SZARRAY_U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SMO;

#endif  //_SMO_H_
