//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _MATHFUNCS_H_
#define _MATHFUNCS_H_

#include <TinyCLR_Interop.h>
struct Library_MathFuncs_CMSIS_Support
{
    TINYCLR_NATIVE_DECLARE(ConvertFloatToInt___STATIC__I4__R4);
    TINYCLR_NATIVE_DECLARE(ConvertIntToFloat___STATIC__R4__I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MathFuncs;

#endif  //_MATHFUNCS_H_
