//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "MathFuncs.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_MathFuncs_CMSIS_Support::ConvertFloatToInt___STATIC__I4__R4,
    Library_MathFuncs_CMSIS_Support::ConvertIntToFloat___STATIC__R4__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MathFuncs =
{
    "MathFuncs", 
    0x471CC572,
    method_lookup
};

