//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "MathFuncs.h"
#include "MathFuncs_CMSIS_Support.h"

using namespace CMSIS;


HRESULT Library_MathFuncs_CMSIS_Support::ConvertFloatToInt___STATIC__I4__R4( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        float param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_float( stack, 0, param0 ) );

        INT32 retVal = Support::ConvertFloatToInt( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_MathFuncs_CMSIS_Support::ConvertIntToFloat___STATIC__R4__I4( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        INT32 param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        float retVal = Support::ConvertIntToFloat( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_float( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}
