//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _MATHFUNCS_H_
#define _MATHFUNCS_H_

#include <TinyCLR_Interop.h>
struct Library_MathFuncs_CMSIS_Matrix
{
    static const int FIELD__rows = 1;
    static const int FIELD__cols = 2;
    static const int FIELD__data = 3;


    //--//

};

struct Library_MathFuncs_CMSIS_MatrixFuncs
{
    TINYCLR_NATIVE_DECLARE(MatrixSub_Nat___STATIC__VOID__U2__U2__SZARRAY_I4__U2__U2__SZARRAY_I4__BYREF_U2__BYREF_U2__SZARRAY_I4);
    TINYCLR_NATIVE_DECLARE(MatrixAdd_Nat___STATIC__VOID__U2__U2__SZARRAY_I4__U2__U2__SZARRAY_I4__BYREF_U2__BYREF_U2__SZARRAY_I4);
    TINYCLR_NATIVE_DECLARE(MatrixMult_Nat___STATIC__VOID__U2__U2__SZARRAY_I4__U2__U2__SZARRAY_I4__BYREF_U2__BYREF_U2__SZARRAY_I4);

    //--//

};

struct Library_MathFuncs_CMSIS_Support
{
    TINYCLR_NATIVE_DECLARE(ConvertFloatToQ31___STATIC__I4__R4);
    TINYCLR_NATIVE_DECLARE(ConvertQ31ToFloat___STATIC__R4__I4);
    TINYCLR_NATIVE_DECLARE(ConvertFloatToQ31___STATIC__VOID__SZARRAY_R4__SZARRAY_I4);
    TINYCLR_NATIVE_DECLARE(ConvertQ31ToFloat___STATIC__VOID__SZARRAY_I4__SZARRAY_R4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MathFuncs;

#endif  //_MATHFUNCS_H_
