//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "ExampleLib.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_ExampleLib_ExampleLib_Exe::OnePlusTwo___I4,
    Library_ExampleLib_ExampleLib_Exe::TwoPlusFour___I4,
    Library_ExampleLib_ExampleLib_Exe::Arg1PlusArg2___I4__I4__I4,
    Library_ExampleLib_ExampleLib_Exe::Arg1PlusArg2_IntFunc___I4__I4__I4,
    Library_ExampleLib_ExampleLib_Exe::IntExp_Lib___I4__I4__I4,
    NULL,
    Library_ExampleLib_ExampleLib_Exe::CustomArgsIO_Int___I4__U2__SZARRAY_U2__U2__SZARRAY_U2,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ExampleLib =
{
    "ExampleLib", 
    0x4E997675,
    method_lookup
};

