//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _EXAMPLELIB_H_
#define _EXAMPLELIB_H_

#include <TinyCLR_Interop.h>
struct Library_ExampleLib_ExampleLib_Exe
{
    TINYCLR_NATIVE_DECLARE(OnePlusTwo___I4);
    TINYCLR_NATIVE_DECLARE(TwoPlusFour___I4);
    TINYCLR_NATIVE_DECLARE(Arg1PlusArg2___I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(Arg1PlusArg2_IntFunc___I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(IntExp_Lib___I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(CustomArgsIO_Int___I4__U2__SZARRAY_U2__BYREF_U2__SZARRAY_U2);

    //--//

};

struct Library_ExampleLib_ExampleLib_Exe__Arg
{
    static const int FIELD__size = 1;
    static const int FIELD__array = 2;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ExampleLib;

#endif  //_EXAMPLELIB_H_
