//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "ExampleLib.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_ExampleLib_ExampleLib_Exe::OnePlusTwo___I4,
    Library_ExampleLib_ExampleLib_Exe::TwoPlusFour___I4,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ExampleLib =
{
    "ExampleLib", 
    0x4BD26F10,
    method_lookup
};

